### ISSUE TITLE
Snark key download interruptions

### ISSUE THREAD

**Issue by JChanceHud** [zkopru-network/zkopru#138]
When the snark key download is interrupted (for example by closing the program) the download does not resume or restart on next run.

The wallet should detect corrupt snark keyfiles using a checksum or similar and automatically restart the download.

**Comment by 78051301012** [comment]
https://api.etherscan.io/api?module=transaction&action=gettxreceiptstatus&txhash=0x513c1ba0bebf66436b5fed86ab668452b7805593c05073eb2d51d3a52f480a76&apikey=YourApiKeyToken

**Comment by 78051301012** [comment]
plis help

**Comment by 78051301012** [comment]
https://api.etherscan.io/api?module=transaction&action=gettxreceiptstatus&txhash=0x513c1ba0bebf66436b5fed86ab668452b7805593c05073eb2d51d3a52f480a76&apikey=YourApiKeyToken

**Comment by JChanceHud** [comment]
This is actually closed by #193
