### ISSUE TITLE
Genesis proposal

### ISSUE THREAD

**Issue by JChanceHud** [zkopru-network/zkopru#162]
The genesis proposal exists but has no `proposalData`. This causes [`getBlock(hash: Bytes32)`](https://github.com/zkopru-network/zkopru/blob/develop/packages/core/src/context/layer2.ts#L78) to return `null` when requesting a valid hash (the first block hash).

@wanseob How should this be handled? I was thinking the `Block` class could have a special case where empty `tx` data returns a `Block` object with empty data.

**Comment by wanseob** [comment]
@JChanceHud I agree with you, I think it'll be good to add the "genesis block" case using if statement or something else.
