### ISSUE TITLE
Burn auction bid front-running

### ISSUE THREAD

**Issue by JChanceHud** [zkopru-network/zkopru#176]
The current burn auction requires each bid increase by a minimum of 10%. This causes large jumps in the bid prices as the price gets higher, e.g. `1 Eth -> 1.1 -> 1.21`.

Say that a user Bob is bidding on a round X. Bob is bidding 1 Ether expecting the profitability of the round to be about 1.05 Ether. Alice sees this bid and sends the same bid but with a gas price that is marginally higher. Unless Bob is watching the mempool Alice will win the bid and get the right to produce blocks for the round. Bob cannot submit another bid without going higher than the projected profit.

The proposed solution is removing the required 10% increase in bid amount. This would allow bids to increase by as little as 1 wei. This effectively removes the concept of "stealing a bid" because a new bid can be made without requiring a 10% increase.

Alternatively clients could simply be implemented with the expectation that gas price wars will occur for certain bids. e.g. Bob and Alice submit many transactions for the same bid with different gas prices until one user determines that the gas price of the transaction + the bid amount is less than the projected profit.

**Comment by wanseob** [comment]
That makes sense so, the 10 % jump offers a **quantal profitability** and it gives an **explicit front-running incentive.** Let's fix the code as you suggested.
