### ISSUE TITLE
Move to typechain 2.x

### ISSUE THREAD

**Issue by JChanceHud** [zkopru-network/zkopru#180]
Typechain 1.x does not support function overloading in Solidity contracts. This is causing compile errors in the burn auction modules, specifically [`bid()`](https://github.com/zkopru-network/zkopru/blob/develop/packages/contracts/contracts/consensus/BurnAuction.sol#L57) and `refund()`.

**Comment by wanseob** [comment]
Hey @JChanceHud  please pull this branch to your working branch
https://github.com/wanseob/zkopru/tree/fix/180

**Comment by wanseob** [comment]
It's been included in the `devleop` branch now

**Comment by wanseob** [comment]
closed by 41b38e875a833174002fa6077791d77ca3c71bb8
