### ISSUE TITLE
Prepay expiration date

### ISSUE THREAD

**Issue by JChanceHud** [zkopru-network/zkopru#203]
We should add a feature that sets an expiration date on a prepay/instant withdraw request.

Currently an attacker can wait until the last moment in the challenge period to collect the instant withdraw reward without having to lock funds for very long. For example, if the challenge period is 7 days an attacker can wait 6.9999 days to perform the prepay and collect the reward.

**Comment by wanseob** [comment]
@JChanceHud I'm working on this issue :)
