### ISSUE TITLE
Backup encryption scheme

### ISSUE THREAD

**Issue by JChanceHud** [zkopru-network/zkopru#204]
To use a Zkopru wallet a user must backup their UTXO notes somehow. Using Metamask we cannot access the user Ethereum private key but we can sign arbitrary data.

Ideally when we backup UTXOs we use symmetric encryption like AES with an automatically generated key. This could be a certain string signed by the Ethereum private key.

Using this system a user can be phished by another website asking them to sign the same data. For example, zk.money uses the public address signed by the private key as the encryption key. This can be easily phished as a user probably won't think twice about signing their own public key.

The question is, how do we create a backup scheme without a user selected password that is not vulnerable to phishing. Also, what level of phishing vulnerability is acceptable?

**Comment by wanseob** [comment]
BTW, it seems the phishing attack can be mitigated by using the signTypedData spec.

* https://docs.metamask.io/guide/signing-data.html#sign-typed-data-v4
* https://eips.ethereum.org/EIPS/eip-712
Not a perfect solution but looks much better.

**Comment by wanseob** [comment]
We can consider these two apis for UTXO backup :)
https://docs.metamask.io/guide/rpc-api.html#eth-decrypt
https://docs.metamask.io/guide/rpc-api.html#eth-decrypt
