### ISSUE TITLE
Ignored `gas` and `gasPrice` using `getSignedTransaction` method.

### ISSUE THREAD

**Issue by sifnoc** [zkopru-network/zkopru#212]
**Describe the bug**

`gas` and `gasPrice` arguments are ignored when sending transaction with using `sendTx` in `packages/contract/src/tx-util.ts`.

Let assume that sending a note with `sendTx` method like below.

```typescript
 const receipt = await wallet.node.layer1.sendTx(
      depositTx,
      accounts[1].ethAccount,
      {
        value: note
          .eth()
          .add(fee)
          .toString(),
        gasPrice: 40000000000,
        gas: 1000000,
      },
    )
```

`gasPrice: 40000000000` and `gas: 1000000` are not used in actual sending transaction. 
These are set by `estimatedGas` at this line, not set from arguments.

https://github.com/zkopru-network/zkopru/blob/97e315952badf645dacf0da6af61dff6c662ece1/packages/contracts/src/tx-util.ts#L24-L30

**Expected behavior**
As followed `Payable` or `NonPayable` type, It should be the same amount of  `gas` and `gasPrice` what this function argument is in a sending transaction.

**Comment by JChanceHud** [comment]
Closed by #214
