### ISSUE TITLE
Flexible Memo Field

### ISSUE THREAD

**Issue by wanseob** [zkopru-network/zkopru#218]
In rollup, as suggested by Vitalik https://ethresear.ch/t/cross-rollup-dex-with-smart-contracts-only-on-the-destination-side/8778
memo field has a lot of potentials.

We are using a fixed size memo field 0 bytes or 81 bytes but want to suggest to use a flexible length of memo field. If user wants to use the memo field, then they should pay for the gas and it's all.

What we have to discuss is

* Currently we have `swapAndMemo` byte field. => we can change this byte filed as a switch like
    * before:
         ```
        bit position: |      0      |      1      |  2  |  3  |  4  |  5  |  6  |  7  |
                       |-------------|-------------|-----|-----|-----|-----|-----|-----|
                       | swap on/off | memo on/off |-----|-----|-----|-----|-----|-----|
        ```
    * new:
        ```
        bit position: |      0      |        1       |        2       |  3  |  4  |  5  |  6  |  7  |
                      |-------------|----------------|----------------|-----|-----|-----|-----|-----|
                      | swap on/off | memo v1 on/off | memo v2 on/off |-----|-----|-----|-----|-----|
        ```
* Then, v1 is the current 81 bytes minimal memo field and v2 means the memo field has the same calldata structure of abi encode/decode.
* do we need to set the max length for the memo field??

**Comment by JChanceHud** [comment]
Can we break backward compatibility and assume the memo is always ABI encoded? Then we can avoid using the memo v2 bit.

I think it's okay to leave the memo field unlimited length, a coordinator can always exclude transactions if they do not pay enough to cover the memo data.

**Comment by wanseob** [comment]
Yes we can but I was concerning about default abi.encode /decode can consume too much default gas for standard tx users. Let's try to calculate the exact amount of gas cost. Before that we have to discuss how to deal with the byte length

First, let's assume we have v1 bit & v2 bit both. In this case,
*  if v1 bit is on, it will parse 81 bytes for the memo field.
* if v2 bit is on, it should parse `n` bytes and set it as the `len` to parse. And parse `len` bytes and set them memo field. Then client can parse the memo field using abi decode if they have the proper abi interface for it.
If we set `n = 1` => 256 bytes is the max for the memo field.
If we set `n = 2` => 65536 bytes becomes the max for the memo field. This looks enough definitely :)

Otherwise if we break the backward compatibility
* if memo bit on, parse `n` bytes for the len of memo field
* parse `len` bytes for the memo field.
* memo field data should contain 4bytes of function sig + 32 bytes * 4 (uint256, uint256, uint128, uint1) for the abi spec.
* Total additional data for memo field for standard tx will be 134 bytes (if we assume `n=2`)

So if we use v1 bit & v2 bit we can save 52 bytes and that is about 10% of the standard tx calldata. How do you think?

**Comment by JChanceHud** [comment]
I'm kinda confused about why the function sig is included in the second section above? 52 bytes of savings is significant in calldata, but I imagine a lot of those bytes will be zeroes which cost significantly less in terms of gas. Also, the savings would only occur when we use v1 encoding, anytime we want to include extra data we'd use v2 anyway (which may be often in the future).

Also, do we need to specify how to decode the memo data in v2 (is that the purpose of the function sig)? Will we define a standard set of fields for memos? I was thinking we could have a byte specifying how to decode the memo (e.g. 256 different structs could be encoded/decoded using abiencoderv2). We could then add custom memo formats in the future without having to update/break anything.

**Comment by wanseob** [comment]
> Also, do we need to specify how to decode the memo data in v2 (is that the purpose of the function sig)?
Yes, that was the purpose. I thought that it'll be good to have 4 bytes sig rather than a 1-byte field. For about this, we can use the struct hashing algorithm in [EIP-721](https://eips.ethereum.org/EIPS/eip-712) and use the first 4 bytes instead of its full 32 bytes to save the cost.

And also, as you pointed out most of the zero bytes costed only a little. Here's my exact testing result
https://github.com/wanseob/memo-field-gas-tester

* v1 costs 1296 gas
* v2 costs 1732 gas = 1636 gas (abi encoded data) + 64 gas (4 bytes sig) + 32 gas (2 bytes for data length)
* diff: 436 gas

436 gas is still about the 5% of the standard tx gas cost so good to keep the backward compatibility.
