### ISSUE TITLE
follow prisma batch transaction support

### ISSUE THREAD

**Issue by wanseob** [zkopru-network/zkopru#22]
The current system is using Prisma for its database layer.

But the current version of Prisma has a lack of transaction support and it causes the bottle-neck in the merkle tree update process. The following two cases especially need to be updated with that feature.

1. SMT update
https://github.com/wanseob/zkopru/blob/e073d6fe03ce0449d10ce9a2537e514c641fe3f3/packages/tree/src/nullifier-tree.ts#L174-L187

2. Cached nodes for merkle proof
https://github.com/wanseob/zkopru/blob/e073d6fe03ce0449d10ce9a2537e514c641fe3f3/packages/tree/src/light-rollup-tree.ts#L474-L492

related Prisma issues:

https://github.com/prisma/prisma-client-js/issues/349
https://github.com/prisma/prisma-client-js/issues/667
https://github.com/prisma/specs/issues/356

**Comment by janpio** [comment]
In a related issue, a comment with a possible transaction API was posted and is looking for feedback (or 👍 on the comment): https://github.com/prisma/prisma-client-js/issues/667#issuecomment-643750802
