### ISSUE TITLE
Contract tests are not running

### ISSUE THREAD

**Issue by JChanceHud** [zkopru-network/zkopru#227]
Truffle is executing only 1 test file (usually the poseidon tests). It's unclear how long this has been going on. Currently pinging the truffle team to see if this is by design and if there is any clean way around it.

**Comment by wanseob** [comment]
@JChanceHud 

To separate the logic codes with the core contracts, there exists a separate test-cases directory. You can run 'truffle test' in that directory then it will run the other test cases too.

the contracts/package.json's script defines `yarn test` for the package as `yarn compile && cd test-cases && truffle test` hope it helps!

**Comment by JChanceHud** [comment]
I think this used to work but now when I run `truffle test` in the test-cases dir it only runs poseidon tests.

I found that the poseidon tests used `contract.only()` when testing, is this a development thing?
