### ISSUE TITLE
UTXO discovery

### ISSUE THREAD

**Issue by wanseob** [zkopru-network/zkopru#239]

**Comment by JChanceHud** [comment]
We want to be able to discover all UTXOs during synchronization. Currently we can discover transactions that we've received and nothing else.

For deposits we can use the emitted `Deposit` event and then retrieve the full transaction calldata and parse the deposit UTXO.

```
emit Deposit(Storage.chain.massDepositId, note, fee);
```

For transactions where we are the sender we need to store all the created notes in calldata. Currently we only store the recipient note (e.g. Bob sends Alice 1 Ether. Two notes are output, one for Bob and one for Alice. Currently only Alice's note is stored in calldata). We should add the ability to either derive the resulting note or simply store it in calldata.

This issue could be split into two parts:
1. Deposit UTXO discovery
2. Transfer sender UTXO discovery
