### ISSUE TITLE
Gas estimation issues

### ISSUE THREAD

**Issue by JChanceHud** [zkopru-network/zkopru#245]
The coordinator currently has trouble estimating gas for block proposals and mass deposit commits. I think this is caused by performing a gas estimation when there are no pending deposits, and the transaction being mined after a deposit has been sent. This causes a hash calculation to occur and a number of unaccounted for `sstore` operations.

As a solution we should take the estimated gas cost and add the cost of commtting mass deposits as a constant value.

If this doesn't solve the problem we should take a more complex approach of looking at block contents and applying our own estimation.

**Comment by sifnoc** [comment]
> I think this is caused by performing a gas estimation when there are no pending deposits, and the transaction being mined after a deposit has been sent. This causes a hash calculation to occur and a number of unaccounted for sstore operations.

Good! I have been thinking to solve this issue to 'own estimation' way. 
Can get actual gas usage from an analysis of testnet data on private geth, like #235 .

FYI, I am using fixed gas amounts instead of 'estimated' one for those two methods on testing.

**Comment by JChanceHud** [comment]
Yes, using a constant value would be okay but I think it's best to keep the gas estimation as low as possible (without being under the actual cost) so miners are more willing to include the transaction.

That table is really good though, we can pull the max gas cost from `commitDeposits` and just use that `40,908`.
