### ISSUE TITLE
Light rollup tree range

### ISSUE THREAD

**Issue by JChanceHud** [zkopru-network/zkopru#279]
The light rollup tree throws an error when cached siblings for a leaf outside the current range is requested.

https://github.com/zkopru-network/zkopru/blob/develop/packages/tree/src/light-rollup-tree.ts#L312

The cached nodes are always available, regardless of the start/end specified in the metadata. Is this check necessary? I disabled it and the wallet still generated valid SNARKs.

@wanseob would appreciate some input here

**Comment by wanseob** [comment]
"Light" rollup tree is designed to be used like
"hey I want to sync the tree from index 19177217. Before that index, just ignore them and give me data from the leaf index 19177217"

So `start` means the leaf index where the tree started to sync and `end` means the latest leaf tree. I think throwing error there is still making some sense. If we wanna ignore that check we should have the exact start & end value.

**Comment by JChanceHud** [comment]
Ah, the problem I'm seeing is that as the sync occurs the start value continues to increase. So if I have a UTXO note a leafindex 100 the node will sync to `start: 500`, `end: 800` and now I can't access my note.

This is the bug I'm running into in the wallet. The best way to avoid is this is maybe sync and then discard as we go? e.g. once I know all my UTXO notes, THEN I can start dropping leaves from the start of the tree.

**Comment by wanseob** [comment]
if you have a leaf index 100, then I think the tree should have started the syn before index 100. I think without that we cannot access to the merkle proof that has exact sibling data for the latest root. Hmm am I missing something?
