### ISSUE TITLE
Synchronization does not go beyond 45.12%

### ISSUE THREAD

**Issue by IgorGer55** [zkopru-network/zkopru#326]
**Describe the bug**
Synchronization does not go beyond 45.12%

**To Reproduce**
1. Go to https://zkopru.network/wallet/
2. Click approve to Metamask wallet
3. Then synchronization starts. Which ends at 45.12% and does not reach 100
4. As a result, the wallet cannot be used.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser google chrome
 - Version 96.0.4664.45 

Wallet adress 0xCf7FB3AdC0A9A4E6F7Caff2ca8C365325Fd19277

**Comment by JChanceHud** [comment]
This should be fixed by recent updates to the wallet, feel free to reopen if it isn't
