### ISSUE TITLE
`registerVk` should use the `VerifyingKey` struct

### ISSUE THREAD

**Issue by wanseob** [zkopru-network/zkopru#56]
The file `packages/contracts/contracts/libraries/SNARKs.sol` defines a `VerifyingKey` struct, and `zkSNARKs()` uses it as the type of one of its parameters. The `registerVk()` function in `packages/contracts/contracts/ZkOptimisticRollUp.sol`, however, does not use `VerifyingKey`. For the sake of consistency and simplicity, it should do so.

\- written by @weijiekoh

**Comment by wanseob** [comment]
https://github.com/zkopru-network/zkopru/blob/cda87e4dbc0f0c835d3d3abc9a5913dcaf4b3ec0/packages/contracts/contracts/ZkOptimisticRollUp.sol#L34-L52

@weijiekoh Line 44, it seems it's already using VerifyingKey struct. Would you please check this?

**Comment by weijiekoh** [comment]
Ah, I meant to suggest:

```
 function registerVk( 
     uint8 numOfInputs, 
     uint8 numOfOutputs, 
     SnarksVerifier.VerifyingKey memory vk
 ) public onlySetupWizard {
```

**Comment by wanseob** [comment]
Thank you Weijie, However, only internal function supports "struct" as its parameter. Is this changed?

**Comment by weijiekoh** [comment]
Hmm, I managed to write public functions where a parameter is a struct in Solidity 0.5.0. e.g.: https://github.com/appliedzkp/maci/blob/master/contracts/sol/MACI.sol#L256

```
    function signUp(
        PubKey memory _userPubKey,
        bytes memory _signUpGatekeeperData,
        bytes memory _initialVoiceCreditProxyData
    ) 
```

**Comment by wanseob** [comment]
0b75d455cc27cd22268396a93a9cb500116763ea closes this issue
