### ISSUE TITLE
It is possible to finalise a block before the challenge period is over

### ISSUE THREAD

**Issue by wanseob** [zkopru-network/zkopru#68]
The `finalize()` function in `packages/contracts/contracts/controllers/Coordinatable.sol` does not check whether the challenge period is over before it finalises a block. A user could withdraw a note from a block containing an invalid transaction.

\- written by @weijiekoh

**Comment by weijiekoh** [comment]
I believe that this issue is in the contract code, but this PR only modifies `coordinator.ts`. Were the contracts modified elsewhere?

**Comment by wanseob** [comment]
Oops commit is been mixed up.
https://github.com/zkopru-network/zkopru/commit/3a3692fb729be52dd4df1d57f5b63402dea171e1

This prev commit closes this issue and this is the following typescript change for that commit. Thanks!!
