### ISSUE TITLE
`propose()` should reject ommer (uncle) proposals

### ISSUE THREAD

**Issue by wanseob** [zkopru-network/zkopru#69]
The block header has a `parentBlock` field. `propose()` stores its value in `Layer2.chain.parentOf` as such:

`Layer2.chain.parentOf[currentBlockHash] = _block.header.parentBlock;`

`finalize()` only accepts a block whose `parentBlock` matches `Layer2.chain.latest`, and then sets the proposed block's header hash as `Layer2.chain.latest`.

As such, if a proposer proposes a block whose `header.parentBlock` refers to a block that already has a child block, this block cannot be finalised. Due to mempool congestion, this may occur even if the proposer does not intend to create such an ommer (uncle) block.

To allow the proposer to save gas, consider adding a check to `propose()` to reject blocks whose `header.parentBlock` does not match `Layer2.chain.latest`. This way, a failed `propose()` transaction will revert early and cost less.

\- written by @weijiekoh

**Comment by wanseob** [comment]
Here latest block means the latest finalized block. Otherwise propose() block is way behind the "latest" block. => I think I seems good to update the variable name to "finalized"

For example, when the block `0xEEEE` is invalid, a proposer can submit a new 5th block`0xFFFF` that has `0xDDDD` for its parent.
```
[0] - [1] - [2:latest finalized] - [3] - [4:0xDDDD] - [5:0xEEEE]
                                                    - [5:0xFFFF]
```
@weijiekoh  Let me close this issue if you don't have any other ideas :)

**Comment by weijiekoh** [comment]
Question: in the above diagram, block 2 is finalised but blocks 3-5 are not finalised yet.

Is it okay to propose a block even if the parent isn't finalised yet? e.g. let's say that Alice finalises [3] and Bob finalises [4]. Only then does Charlie finalise [5]. Is that an acceptable path?

**Comment by wanseob** [comment]
@weijiekoh Yes, it's okay to propose unfinalized block's child block. And a block only can be finalized when its parent block is finalized.

It is because we have to wait 7 challenge period days when we don't accept the proposal on unfinalized parent blocks

**Comment by weijiekoh** [comment]
I see!!

The proposer should be able to propose a block whose parent is any unfinalised block or the latest finalised block they wish.

Go ahead and close this issue :D

**Comment by wanseob** [comment]
Thank you so much for your review 😍
