### ISSUE TITLE
 Line-by-line audit: Storage contract

### ISSUE THREAD

**Issue by wanseob** [zkopru-network/zkopru#94]
**`contracts/storage/Layer2.sol`**

Line 23: See the audit report section about using a different way to encode the mapping key. `bytes32` could be `uint256` instead.
Line 29: The storage variable `proof` should be renamed to `proofs` to increase code clarity.
Line 99: `getVk()` is unused in the codebase. If it is, however, it should return a `SNARKs.VerifyingKey`.

**`contracts/storage/Configurated.sol`**

Line 9: The challenge period of 7 seconds seems feasible only for testing purposes and not the mainnet. Moreover, the challenge period should be denominated in blocks, not seconds, as a miner can manipulate the block timestamp.

\- written by @weijiekoh

**Comment by barryWhiteHat** [comment]
All times should be denominated in blocks not seconds. Miners can cause clock drive to change the time.

**Comment by wanseob** [comment]
contracts/storage/Layer2.sol

Line 23: 8636a41a08e483af3ccd72b743c0ac505ee99725 resolves
Line 29: 3304f9876d937efd2355d9891924c27738624ef3 resolves
Line 99: `VerifyingKey` includes struct array form (G1Point[]) even experimental ABI V2 doesn't support it yet.
commit 02750c85103545602e296a01da2ad443382fcde6 closes Configurated.sol Line9.

contracts/storage/Configurated.sol

Line 9: 55f3e3d46e66b9aa19cd35416aa827b02cb10f78 resolves
